name: Run Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename JAR and ZIP files
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME//\//-} # Replace slashes with dashes
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          for file in build/libs/*.jar build/libs/*.zip; do
            filename=$(basename "$file")
            extension="${filename##*.}"
            new_name="${filename%.*}-$BRANCH_NAME-$BUILD_NUMBER.$extension"
            mv "$file" "build/libs/$new_name"
          done

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: CatgirlAddons-${{ github.ref_name }}-${{ github.run_number }}
          path: build/libs/*-${{ github.ref_name }}-${{ github.run_number }}.*
